#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WINDOW_WIDTH 540
#define WINDOW_HEIGHT 960

#define PLAYER_INIT_X (540/2-80/2)
#define PLAYER_INIT_Y (750)
#define PLAYER_WIDTH (80)
#define PLAYER_HEIGHT (80)
#define PLAYER_KEY_MOVE (10)

#define PLAYER_JUMP_TIME 500

#define PLAYER_BASIC_JUMP_HEIGHT 320
#define PLAYER_SPRING_JUMP_HEIGHT (960)
#define PLAYER_TRAMPOLINE_JUMP_HEIGHT (1920)
#define PLAYER_PROPELLER_HAT_JUMP_HEIGHT (3840)
#define PLAYER_JETPACK_JUMP_HEIGHT (7680)

#define STAIR_WIDTH 120
#define STAIR_HEIGHT 30

#define THORN_STAIR_WIDTH 94
#define THORN_STAIR_HEIGHT 42

#define BROKEN_STAIR_UNLOCK_ALTITUDE 0
#define BROKEN_STAIR_APPEAR_INTERVAL 1000
#define H_MOVE_STAIR_UNLOCK_ALTITUDE (6000)
#define H_MOVE_STAIR_APPEAR_INTERVAL (3000)
#define V_MOVE_STAIR_UNLOCK_ALTITUDE (6000)
#define V_MOVE_STAIR_APPEAR_INTERVAL (3000)
#define DISAPPEARING_STAIR_UNLOCK_ALTITUDE 9000
#define DISAPPEARING_STAIR_APPEAR_INTERVAL 5000
#define THORN_STAIR_UNLOCK_ALTITUDE 1500
#define THORN_STAIR_APPEAR_INTERVAL 4000
#define COUNTDOWN_STAIR_UNLOCK_ALTITUDE 4500
#define COUNTDOWN_STAIR_APPEAR_INTERVAL 4000

#define ITEM_UNLOCK_ALTITUDE 3000
#define ITEM_APPEAR_INTERVAL WINDOW_HEIGHT * 2

#define MONSTER_UNLOCK_ALTITUDE 1000
#define MONSTER_APPEAR_INTERVAL 5000

#define BULLET_WIDTH 20
#define BULLET_HEIGHT 20
#define BULLET_STEP 40

#define SPRING_WIDTH 40
#define SPRING_HEIGHT 25

#define TRAMPOLINE_WIDTH 72
#define TRAMPOLINE_HEIGHT 36

#define PROPELLER_HAT_WIDTH 64
#define PROPELLER_HAT_HEIGHT 40

#define JETPACK_WIDTH 50
#define JETPACK_HEIGHT 72

#define SPRING_SHOES_WIDTH 97
#define SPRING_SHOES_HEIGHT 66

#define SHIELD_WIDTH 106
#define SHIELD_HEIGHT 107

#define SPRING_SHOES_DURATION 5000

#define GAME_TIMER_INTERVAL 1
#define IS_DEBUG false

#endif // CONSTANTS_H
