#############################################################################
# Makefile for building: doodleJump.exe
# Generated by qmake (3.1) (Qt 5.9.4)
# Project:  doodleJump.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile doodleJump.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -fno-keep-inline-dllexport -D_GNU_SOURCE -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -fno-keep-inline-dllexport -D_GNU_SOURCE -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I/usr/lib/qt5/mkspecs/cygwin-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = doodleJump1.0.0
DISTDIR = /home/0501_DoodleJump/.tmp/doodleJump1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lQt5Multimedia -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = bullet.cpp \
		detections/detection.cpp \
		detections/detection_enter_window.cpp \
		detections/detection_landing.cpp \
		detections/detection_touching.cpp \
		detections/detection_touching_without_landing.cpp \
		detector.cpp \
		gameobject.cpp \
		main.cpp \
		mainwindow.cpp \
		mover.cpp \
		player.cpp \
		reactions/reaction.cpp \
		reactions/reaction_change_image.cpp \
		reactions/reaction_disappear.cpp \
		reactions/reaction_gameover.cpp \
		reactions/reaction_make_sound.cpp \
		reactions/reaction_player_be_attacked.cpp \
		reactions/reaction_player_buffed_jump_height.cpp \
		reactions/reaction_player_jump.cpp \
		reactions/reaction_player_set_flying_state.cpp \
		reactions/reaction_player_shielded.cpp \
		stair_manager.cpp qrc_res.cpp \
		moc_bullet.cpp \
		moc_gameobject.cpp \
		moc_mainwindow.cpp \
		moc_player.cpp \
		moc_reaction_change_image.cpp \
		moc_reaction_player_buffed_jump_height.cpp \
		moc_stair_manager.cpp
OBJECTS       = bullet.o \
		detection.o \
		detection_enter_window.o \
		detection_landing.o \
		detection_touching.o \
		detection_touching_without_landing.o \
		detector.o \
		gameobject.o \
		main.o \
		mainwindow.o \
		mover.o \
		player.o \
		reaction.o \
		reaction_change_image.o \
		reaction_disappear.o \
		reaction_gameover.o \
		reaction_make_sound.o \
		reaction_player_be_attacked.o \
		reaction_player_buffed_jump_height.o \
		reaction_player_jump.o \
		reaction_player_set_flying_state.o \
		reaction_player_shielded.o \
		stair_manager.o \
		qrc_res.o \
		moc_bullet.o \
		moc_gameobject.o \
		moc_mainwindow.o \
		moc_player.o \
		moc_reaction_change_image.o \
		moc_reaction_player_buffed_jump_height.o \
		moc_stair_manager.o
DIST          = /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/cygwin-g++/qmake.conf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt5/mkspecs/features/uic.prf \
		/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		doodleJump.pro bullet.h \
		constants.h \
		detections/detection.h \
		detections/detection_enter_window.h \
		detections/detection_landing.h \
		detections/detection_touching.h \
		detections/detection_touching_without_landing.h \
		detector.h \
		gameobject.h \
		mainwindow.h \
		mover.h \
		player.h \
		reactions/reaction.h \
		reactions/reaction_change_image.h \
		reactions/reaction_disappear.h \
		reactions/reaction_gameover.h \
		reactions/reaction_make_sound.h \
		reactions/reaction_player_be_attacked.h \
		reactions/reaction_player_buffed_jump_height.h \
		reactions/reaction_player_jump.h \
		reactions/reaction_player_set_flying_state.h \
		reactions/reaction_player_shielded.h \
		rule_instances.h \
		stair_manager.h bullet.cpp \
		detections/detection.cpp \
		detections/detection_enter_window.cpp \
		detections/detection_landing.cpp \
		detections/detection_touching.cpp \
		detections/detection_touching_without_landing.cpp \
		detector.cpp \
		gameobject.cpp \
		main.cpp \
		mainwindow.cpp \
		mover.cpp \
		player.cpp \
		reactions/reaction.cpp \
		reactions/reaction_change_image.cpp \
		reactions/reaction_disappear.cpp \
		reactions/reaction_gameover.cpp \
		reactions/reaction_make_sound.cpp \
		reactions/reaction_player_be_attacked.cpp \
		reactions/reaction_player_buffed_jump_height.cpp \
		reactions/reaction_player_jump.cpp \
		reactions/reaction_player_set_flying_state.cpp \
		reactions/reaction_player_shielded.cpp \
		stair_manager.cpp
QMAKE_TARGET  = doodleJump
DESTDIR       = 
TARGET        = doodleJump.exe


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: doodleJump.pro /usr/lib/qt5/mkspecs/cygwin-g++/qmake.conf /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/cygwin-g++/qmake.conf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt5/mkspecs/features/uic.prf \
		/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		doodleJump.pro \
		res.qrc
	$(QMAKE) -o Makefile doodleJump.pro
/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/qt5/mkspecs/common/unix.conf:
/usr/lib/qt5/mkspecs/common/sanitize.conf:
/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/qt5/mkspecs/common/g++-base.conf:
/usr/lib/qt5/mkspecs/qconfig.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/qt5/mkspecs/features/qt_config.prf:
/usr/lib/qt5/mkspecs/cygwin-g++/qmake.conf:
/usr/lib/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt5/mkspecs/features/toolchain.prf:
/usr/lib/qt5/mkspecs/features/default_pre.prf:
/usr/lib/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/qt5/mkspecs/features/default_post.prf:
/usr/lib/qt5/mkspecs/features/warn_on.prf:
/usr/lib/qt5/mkspecs/features/qt.prf:
/usr/lib/qt5/mkspecs/features/resources.prf:
/usr/lib/qt5/mkspecs/features/moc.prf:
/usr/lib/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/qt5/mkspecs/features/uic.prf:
/usr/lib/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/qt5/mkspecs/features/file_copies.prf:
/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/qt5/mkspecs/features/exceptions.prf:
/usr/lib/qt5/mkspecs/features/yacc.prf:
/usr/lib/qt5/mkspecs/features/lex.prf:
doodleJump.pro:
res.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile doodleJump.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents res.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents bullet.h constants.h detections/detection.h detections/detection_enter_window.h detections/detection_landing.h detections/detection_touching.h detections/detection_touching_without_landing.h detector.h gameobject.h mainwindow.h mover.h player.h reactions/reaction.h reactions/reaction_change_image.h reactions/reaction_disappear.h reactions/reaction_gameover.h reactions/reaction_make_sound.h reactions/reaction_player_be_attacked.h reactions/reaction_player_buffed_jump_height.h reactions/reaction_player_jump.h reactions/reaction_player_set_flying_state.h reactions/reaction_player_shielded.h rule_instances.h stair_manager.h $(DISTDIR)/
	$(COPY_FILE) --parents bullet.cpp detections/detection.cpp detections/detection_enter_window.cpp detections/detection_landing.cpp detections/detection_touching.cpp detections/detection_touching_without_landing.cpp detector.cpp gameobject.cpp main.cpp mainwindow.cpp mover.cpp player.cpp reactions/reaction.cpp reactions/reaction_change_image.cpp reactions/reaction_disappear.cpp reactions/reaction_gameover.cpp reactions/reaction_make_sound.cpp reactions/reaction_player_be_attacked.cpp reactions/reaction_player_buffed_jump_height.cpp reactions/reaction_player_jump.cpp reactions/reaction_player_set_flying_state.cpp reactions/reaction_player_shielded.cpp stair_manager.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		/usr/lib/qt5/bin/rcc \
		dataset/images/monster2.png \
		dataset/images/item-propeller-hat.png \
		dataset/images/monster3.png \
		dataset/images/materials-propeller.png \
		dataset/images/monster4.png \
		dataset/images/bgOriginal.png \
		dataset/images/background.png \
		dataset/images/stair-basic.png \
		dataset/images/doodleL.png \
		dataset/images/doodleUL.png \
		dataset/images/stair-broken1.png \
		dataset/images/item-jetpack.png \
		dataset/images/stair-broken2.png \
		dataset/images/doodleUR.png \
		dataset/images/doodleR.png \
		dataset/images/stair-broken3.png \
		dataset/images/stair-darkblue.png \
		dataset/images/doodleS.png \
		dataset/images/stair-blue.png \
		dataset/images/stair-broken4.png \
		dataset/images/materials-spring-shoes.png \
		dataset/images/stair-disapear.png \
		dataset/images/bullet.png \
		dataset/images/reference-start-interface.png \
		dataset/images/materials-jetpack.png \
		dataset/images/item-trampoline1.png \
		dataset/images/item-trampoline2.png \
		dataset/images/item-trampoline3.png \
		dataset/images/blackhole.png \
		dataset/images/item-spring1.png \
		dataset/images/item-spring2.png \
		dataset/images/materials.png \
		dataset/images/monster1.png \
		dataset/images/doodleSpring/doodleSpringR.png \
		dataset/images/doodleSpring/doodleSpring.png \
		dataset/images/doodleJ/doodleJ1.png \
		dataset/images/doodleJ/doodleJ5R.png \
		dataset/images/doodleJ/doodleJ5.png \
		dataset/images/doodleJ/doodleJ9.png \
		dataset/images/doodleJ/doodleJ10.png \
		dataset/images/doodleJ/doodleJ1R.png \
		dataset/images/doodleJ/doodleJ4.png \
		dataset/images/doodleJ/doodleJ4R.png \
		dataset/images/doodleJ/doodleJ8.png \
		dataset/images/doodleJ/doodleJ3.png \
		dataset/images/doodleJ/doodleJ7.png \
		dataset/images/doodleJ/doodleJ3R.png \
		dataset/images/doodleJ/doodleJ2.png \
		dataset/images/doodleJ/doodleJ6.png \
		dataset/images/doodleJ/doodleJ2R.png \
		dataset/images/extra/item-spring-shoes.png \
		dataset/images/extra/heart.png \
		dataset/images/extra/stair-countdown3.png \
		dataset/images/extra/button_resume.png \
		dataset/images/extra/button_multiplayer.png \
		dataset/images/extra/doodleL2.png \
		dataset/images/extra/stair-thorn.png \
		dataset/images/extra/stair-countdown2.png \
		dataset/images/extra/doodleR2.png \
		dataset/images/extra/item-shield.png \
		dataset/images/extra/shielded.png \
		dataset/images/extra/logo.png \
		dataset/images/extra/stair-countdown1.png \
		dataset/images/extra/UFO.png \
		dataset/images/extra/button_play.png \
		dataset/images/extra/button_menu.png \
		dataset/images/doodleH/doodleH3.png \
		dataset/images/doodleH/doodleH2R.png \
		dataset/images/doodleH/doodleH2.png \
		dataset/images/doodleH/doodleH1R.png \
		dataset/images/doodleH/doodleH4R.png \
		dataset/images/doodleH/doodleH1.png \
		dataset/images/doodleH/doodleH3R.png \
		dataset/images/doodleH/doodleH4.png \
		dataset/sounds/propeller.wav \
		dataset/sounds/spring.wav \
		dataset/sounds/rocket.wav \
		dataset/sounds/falldown.wav \
		dataset/sounds/jump.wav \
		dataset/sounds/trampoline.mp3 \
		dataset/sounds/break.wav \
		dataset/sounds/jumponmonster.mp3 \
		dataset/sounds/shoot.mp3
	/usr/lib/qt5/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt5/mkspecs/features/data/dummy.cpp
	g++ -fno-keep-inline-dllexport -D_GNU_SOURCE -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_bullet.cpp moc_gameobject.cpp moc_mainwindow.cpp moc_player.cpp moc_reaction_change_image.cpp moc_reaction_player_buffed_jump_height.cpp moc_stair_manager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_bullet.cpp moc_gameobject.cpp moc_mainwindow.cpp moc_player.cpp moc_reaction_change_image.cpp moc_reaction_player_buffed_jump_height.cpp moc_stair_manager.cpp
moc_bullet.cpp: gameobject.h \
		mover.h \
		constants.h \
		bullet.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt5/mkspecs/cygwin-g++ -I/home/0501_DoodleJump -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++ -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/x86_64-pc-cygwin -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/backward -I/usr/lib/gcc/x86_64-pc-cygwin/11/include -I/usr/include -I/usr/include/w32api bullet.h -o moc_bullet.cpp

moc_gameobject.cpp: mover.h \
		constants.h \
		gameobject.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt5/mkspecs/cygwin-g++ -I/home/0501_DoodleJump -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++ -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/x86_64-pc-cygwin -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/backward -I/usr/lib/gcc/x86_64-pc-cygwin/11/include -I/usr/include -I/usr/include/w32api gameobject.h -o moc_gameobject.cpp

moc_mainwindow.cpp: constants.h \
		gameobject.h \
		mover.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h \
		reactions/reaction.h \
		detector.h \
		detections/detection.h \
		stair_manager.h \
		reactions/reaction_change_image.h \
		mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt5/mkspecs/cygwin-g++ -I/home/0501_DoodleJump -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++ -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/x86_64-pc-cygwin -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/backward -I/usr/lib/gcc/x86_64-pc-cygwin/11/include -I/usr/include -I/usr/include/w32api mainwindow.h -o moc_mainwindow.cpp

moc_player.cpp: constants.h \
		gameobject.h \
		mover.h \
		bullet.h \
		reactions/reaction_make_sound.h \
		reactions/reaction.h \
		player.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt5/mkspecs/cygwin-g++ -I/home/0501_DoodleJump -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++ -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/x86_64-pc-cygwin -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/backward -I/usr/lib/gcc/x86_64-pc-cygwin/11/include -I/usr/include -I/usr/include/w32api player.h -o moc_player.cpp

moc_reaction_change_image.cpp: reactions/reaction.h \
		gameobject.h \
		mover.h \
		constants.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h \
		reactions/reaction_change_image.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt5/mkspecs/cygwin-g++ -I/home/0501_DoodleJump -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++ -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/x86_64-pc-cygwin -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/backward -I/usr/lib/gcc/x86_64-pc-cygwin/11/include -I/usr/include -I/usr/include/w32api reactions/reaction_change_image.h -o moc_reaction_change_image.cpp

moc_reaction_player_buffed_jump_height.cpp: reactions/reaction.h \
		gameobject.h \
		mover.h \
		constants.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h \
		reactions/reaction_player_buffed_jump_height.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt5/mkspecs/cygwin-g++ -I/home/0501_DoodleJump -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++ -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/x86_64-pc-cygwin -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/backward -I/usr/lib/gcc/x86_64-pc-cygwin/11/include -I/usr/include -I/usr/include/w32api reactions/reaction_player_buffed_jump_height.h -o moc_reaction_player_buffed_jump_height.cpp

moc_stair_manager.cpp: constants.h \
		gameobject.h \
		mover.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h \
		reactions/reaction.h \
		detector.h \
		detections/detection.h \
		reactions/reaction_change_image.h \
		stair_manager.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt5/mkspecs/cygwin-g++ -I/home/0501_DoodleJump -I/usr/include/qt5 -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++ -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/x86_64-pc-cygwin -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/backward -I/usr/lib/gcc/x86_64-pc-cygwin/11/include -I/usr/include -I/usr/include/w32api stair_manager.h -o moc_stair_manager.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

bullet.o: bullet.cpp bullet.h \
		gameobject.h \
		mover.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bullet.o bullet.cpp

detection.o: detections/detection.cpp detections/detection.h \
		gameobject.h \
		mover.h \
		constants.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h \
		reactions/reaction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detection.o detections/detection.cpp

detection_enter_window.o: detections/detection_enter_window.cpp detections/detection_enter_window.h \
		detections/detection.h \
		gameobject.h \
		mover.h \
		constants.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h \
		reactions/reaction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detection_enter_window.o detections/detection_enter_window.cpp

detection_landing.o: detections/detection_landing.cpp detections/detection_landing.h \
		detections/detection.h \
		gameobject.h \
		mover.h \
		constants.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h \
		reactions/reaction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detection_landing.o detections/detection_landing.cpp

detection_touching.o: detections/detection_touching.cpp detections/detection_touching.h \
		detections/detection.h \
		gameobject.h \
		mover.h \
		constants.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h \
		reactions/reaction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detection_touching.o detections/detection_touching.cpp

detection_touching_without_landing.o: detections/detection_touching_without_landing.cpp detections/detection_touching_without_landing.h \
		detections/detection.h \
		gameobject.h \
		mover.h \
		constants.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h \
		reactions/reaction.h \
		detections/detection_touching.h \
		detections/detection_landing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detection_touching_without_landing.o detections/detection_touching_without_landing.cpp

detector.o: detector.cpp detector.h \
		constants.h \
		gameobject.h \
		mover.h \
		detections/detection.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h \
		reactions/reaction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detector.o detector.cpp

gameobject.o: gameobject.cpp gameobject.h \
		mover.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameobject.o gameobject.cpp

main.o: main.cpp mainwindow.h \
		constants.h \
		gameobject.h \
		mover.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h \
		reactions/reaction.h \
		detector.h \
		detections/detection.h \
		stair_manager.h \
		reactions/reaction_change_image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		constants.h \
		gameobject.h \
		mover.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h \
		reactions/reaction.h \
		detector.h \
		detections/detection.h \
		stair_manager.h \
		reactions/reaction_change_image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

mover.o: mover.cpp mover.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mover.o mover.cpp

player.o: player.cpp player.h \
		constants.h \
		gameobject.h \
		mover.h \
		bullet.h \
		reactions/reaction_make_sound.h \
		reactions/reaction.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

reaction.o: reactions/reaction.cpp reactions/reaction.h \
		gameobject.h \
		mover.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reaction.o reactions/reaction.cpp

reaction_change_image.o: reactions/reaction_change_image.cpp reactions/reaction_change_image.h \
		reactions/reaction.h \
		gameobject.h \
		mover.h \
		constants.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reaction_change_image.o reactions/reaction_change_image.cpp

reaction_disappear.o: reactions/reaction_disappear.cpp reactions/reaction_disappear.h \
		reactions/reaction.h \
		gameobject.h \
		mover.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reaction_disappear.o reactions/reaction_disappear.cpp

reaction_gameover.o: reactions/reaction_gameover.cpp reactions/reaction_gameover.h \
		reactions/reaction.h \
		gameobject.h \
		mover.h \
		constants.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reaction_gameover.o reactions/reaction_gameover.cpp

reaction_make_sound.o: reactions/reaction_make_sound.cpp reactions/reaction_make_sound.h \
		reactions/reaction.h \
		gameobject.h \
		mover.h \
		constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reaction_make_sound.o reactions/reaction_make_sound.cpp

reaction_player_be_attacked.o: reactions/reaction_player_be_attacked.cpp reactions/reaction_player_be_attacked.h \
		reactions/reaction.h \
		gameobject.h \
		mover.h \
		constants.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reaction_player_be_attacked.o reactions/reaction_player_be_attacked.cpp

reaction_player_buffed_jump_height.o: reactions/reaction_player_buffed_jump_height.cpp reactions/reaction_player_buffed_jump_height.h \
		reactions/reaction.h \
		gameobject.h \
		mover.h \
		constants.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reaction_player_buffed_jump_height.o reactions/reaction_player_buffed_jump_height.cpp

reaction_player_jump.o: reactions/reaction_player_jump.cpp reactions/reaction_player_jump.h \
		reactions/reaction.h \
		gameobject.h \
		mover.h \
		constants.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reaction_player_jump.o reactions/reaction_player_jump.cpp

reaction_player_set_flying_state.o: reactions/reaction_player_set_flying_state.cpp reactions/reaction_player_set_flying_state.h \
		reactions/reaction.h \
		gameobject.h \
		mover.h \
		constants.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reaction_player_set_flying_state.o reactions/reaction_player_set_flying_state.cpp

reaction_player_shielded.o: reactions/reaction_player_shielded.cpp reactions/reaction_player_shielded.h \
		reactions/reaction.h \
		gameobject.h \
		mover.h \
		constants.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reaction_player_shielded.o reactions/reaction_player_shielded.cpp

stair_manager.o: stair_manager.cpp stair_manager.h \
		constants.h \
		gameobject.h \
		mover.h \
		player.h \
		bullet.h \
		reactions/reaction_make_sound.h \
		reactions/reaction.h \
		detector.h \
		detections/detection.h \
		reactions/reaction_change_image.h \
		rule_instances.h \
		detections/detection_landing.h \
		detections/detection_touching.h \
		detections/detection_touching_without_landing.h \
		detections/detection_enter_window.h \
		reactions/reaction_disappear.h \
		reactions/reaction_player_jump.h \
		reactions/reaction_player_be_attacked.h \
		reactions/reaction_player_set_flying_state.h \
		reactions/reaction_player_buffed_jump_height.h \
		reactions/reaction_player_shielded.h \
		reactions/reaction_gameover.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stair_manager.o stair_manager.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

moc_bullet.o: moc_bullet.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bullet.o moc_bullet.cpp

moc_gameobject.o: moc_gameobject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gameobject.o moc_gameobject.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_player.o: moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_player.o moc_player.cpp

moc_reaction_change_image.o: moc_reaction_change_image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_reaction_change_image.o moc_reaction_change_image.cpp

moc_reaction_player_buffed_jump_height.o: moc_reaction_player_buffed_jump_height.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_reaction_player_buffed_jump_height.o moc_reaction_player_buffed_jump_height.cpp

moc_stair_manager.o: moc_stair_manager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stair_manager.o moc_stair_manager.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/doodleJump/bin || mkdir -p $(INSTALL_ROOT)/opt/doodleJump/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET).exe $(INSTALL_ROOT)/opt/doodleJump/bin/$(QMAKE_TARGET).exe

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/doodleJump/bin/$(QMAKE_TARGET).exe
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/doodleJump/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

